// Model.js

var Model = [
	{
		path:"labs/01/dist/index.html",
		cover:"dist/assets/covers/00.jpg"
	},{
		path:"labs/wen/02/dist/index.html",
		cover:"dist/assets/covers/01.jpg"
	},
	{
		path:"labs/wen/04/dist/index.html",
		cover:"dist/assets/covers/02.jpg"
	},
	{
		path:"labs/wen/05/dist/index.html",
		cover:"dist/assets/covers/03.jpg"
	},
	{
		path:"labs/wen/06/dist/index.html",
		cover:"dist/assets/covers/04.jpg"
	},
	{
		path:"labs/wen/07/dist/index.html",
		cover:"dist/assets/covers/05.jpg"
	},
	{
		path:"labs/wen/08/dist/index.html",
		cover:"dist/assets/covers/06.jpg"
	},
	{
		path:"labs/cp/08/dist/index.html",
		cover:"dist/assets/covers/cp08.jpg"
	},
	{
		path:"labs/wen/09/dist/index.html",
		cover:"dist/assets/covers/07.jpg"
	},
	{
		path:"labs/cp/10/dist/index.html",
		cover:"dist/assets/covers/cp10.jpg"
	},
	{
		path:"labs/wen/10/dist/index.html",
		cover:"dist/assets/covers/wen08.jpg"
	},
	{
		path:"labs/wen/11/dist/index.html",
		cover:"dist/assets/covers/wen09.jpg"
	},
	{
		path:"labs/wen/12/dist/index.html",
		cover:"dist/assets/covers/wen10.jpg"
	},
	{
		path:"labs/cp/12/dist/index.html",
		cover:"dist/assets/covers/cp12.jpg"
	},
	{
		path:"labs/wen/16_swirlingParticles/dist/index.html",
		cover:"dist/assets/covers/wen11.jpg"
	},
	{
		path:"labs/wen/18_ripple/dist/index.html",
		cover:"dist/assets/covers/wen12.jpg"
	},
	{
		path:"labs/wen/20_sphereParticles/dist/index.html",
		cover:"dist/assets/covers/wen13.jpg"
	},
	{
		path:"labs/wen/22_refractions/dist/index.html",
		cover:"dist/assets/covers/wen14.jpg"
	},
	{
		path:"labs/wen/23_breakingSphere/dist/index.html",
		cover:"dist/assets/covers/wen15.jpg"
	}
];

module.exports = Model;