const ExpModel = [
	{
		cover:'assets/img/cover01.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/01/dist/index.html',
		title:'Vortex'
	},
	{
		cover:'assets/img/cover02.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/02/dist/index.html',
		title:'Flow'
	},
	{
		cover:'assets/img/cover03.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/03/dist/index.html',
		title:'Portrait'
	},
	{
		cover:'assets/img/cover04.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/04/dist/index.html',
		title:'Tower'
	},
	{
		cover:'assets/img/cover05.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/05/dist/index.html',
		title:'Sphere'
	},
	{
		cover:'assets/img/cover06.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/06/dist/index.html',
		title:'Cubes'
	},
	{
		cover:'assets/img/cover07.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/07/dist/index.html',
		title:'Feather'
	},
	{
		cover:'assets/img/cover08.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/08/dist/index.html',
		title:'Swarm'
	},
	{
		cover:'assets/img/cover09.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/09/dist/index.html',
		title:'Mirror'
	},
	{
		cover:'assets/img/cover10.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/10/dist/index.html',
		title:'Zoetrope'
	},
	{
		cover:'assets/img/cover11.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/11/dist/index.html',
		title:'Storms'
	},
	{
		cover:'assets/img/cover12.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/12/dist/index.html',
		title:'Storms'
	},
	{
		cover:'assets/img/cover13.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/13/dist/index.html',
		title:'Running'
	},
	{
		cover:'assets/img/cover14.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/14/dist/index.html',
		title:'Swirling'
	},
	{
		cover:'assets/img/cover15.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/15/dist/index.html',
		title:'Wing'
	},
	{
		cover:'assets/img/cover16.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/16/dist/index.html',
		title:'Cubes'
	},
	{
		cover:'assets/img/cover17.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/17/dist/index.html',
		title:'Shadows'
	},
	{
		cover:'assets/img/cover18.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/18/dist/index.html',
		title:'Tunnel'
	},
	{
		cover:'assets/img/cover19.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/19/dist/index.html',
		title:'Flocking'
	},
	{
		cover:'assets/img/cover20.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/20/dist/index.html',
		title:'Dissolve'
	},
	{
		cover:'assets/img/cover21.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/21/dist/index.html',
		title:'City'
	},
	{
		cover:'assets/img/cover22.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/22/dist/index.html',
		title:'Day Night'
	},
	{
		cover:'assets/img/cover23.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/23/dist/index.html',
		title:'Paper Plane'
	},
	{
		cover:'assets/img/cover24.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/24/dist/index.html',
		title:'Glass Statue'
	},
	{
		cover:'assets/img/cover25.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/25/dist/index.html',
		title:'Break'
	},
	{
		cover:'assets/img/cover26.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/26/dist/index.html',
		title:'Ying Yang'
	},
	{
		cover:'assets/img/cover27.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/27/dist/index.html',
		title:'Wolf'
	},
	{
		cover:'assets/img/cover28.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/28/dist/index.html',
		title:'Stage'
	},
	{
		cover:'assets/img/cover29.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/29/dist/index.html',
		title:'Ripples'
	},
	{
		cover:'assets/img/coverFinal.jpg',
		url:'//yiwenl.github.io/Codevember/2017/experiments/30/dist/index.html',
		title:'Taichi'
	}
]



module.exports = ExpModel;
